# docker/compose.yml
name: realtime-social-platform

services:
  # ==========================
  # DATABASES (profiles)
  # ==========================
  db-postgres:
    profiles: ["db-postgres"]
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 5s
      timeout: 3s
      retries: 20

  db-mysql:
    profiles: ["db-mysql"]
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 5s
      timeout: 3s
      retries: 30

  # ==========================
  # BACKENDS (profiles)
  # ==========================
  api-node-sequelize:
    profiles: ["api-node-sequelize"]
    build:
      context: ..
      dockerfile: apps/back/node-sequelize/Dockerfile
    env_file: ../.env
    depends_on:
      db-postgres:
        condition: service_healthy
      db-mysql:
        condition: service_healthy
    ports:
      - "4000:4000"

  api-node-prisma:
    profiles: ["api-node-prisma"]
    build:
      context: ..
      dockerfile: apps/back/node-prisma/Dockerfile
    env_file: ../.env
    depends_on:
      db-postgres:
        condition: service_healthy
      db-mysql:
        condition: service_healthy
    ports:
      - "4000:4000"

  api-java-spring:
    profiles: ["api-java-spring"]
    build:
      context: ..
      dockerfile: apps/back/java-spring/Dockerfile
    env_file: ../.env
    depends_on:
      db-postgres:
        condition: service_healthy
      db-mysql:
        condition: service_healthy
    ports:
      - "4000:4000"

  api-rust-rocket:
    profiles: ["api-rust-rocket"]
    build:
      context: ..
      dockerfile: apps/back/rust-rocket/Dockerfile
    env_file: ../.env
    depends_on:
      db-postgres:
        condition: service_healthy
      db-mysql:
        condition: service_healthy
    ports:
      - "4000:4000"

  # ==========================
  # FRONTS (profiles)
  # ==========================
  web-vue:
    profiles: ["web-vue"]
    build:
      context: ..
      dockerfile: apps/front/vue/Dockerfile
    env_file: ../.env
    ports:
      - "5173:5173"
  

  web-react:
    profiles: ["web-react"]
    build:
      context: ..
      dockerfile: apps/front/react/Dockerfile
    env_file: ../.env
    ports:
      - "5174:5173"

volumes:
  pg_data:
  mysql_data:
