name: realtime-social-platform

services:
  # ==========================
  # DATABASE
  # ==========================
  db-mysql:
    profiles: ["db-mysql"]
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 30

  # ==========================
  # BACKEND
  # ==========================
  api-node-sequelize:
    profiles: ["api-node-sequelize"]
    build:
      context: .
      dockerfile: apps/back/node-sequelize/Dockerfile
    env_file: ./.env
    depends_on:
      db-mysql:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: ["npm", "start"]
  # ==========================
  # FRONT
  # ==========================
  web-vue:
    profiles: ["web-vue"]
    build:
      context: .
      dockerfile: apps/front/vue/Dockerfile
    env_file: ./.env
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"

  web-react:
    profiles: ["web-react"]
    build:
      context: .
      dockerfile: apps/front/react/Dockerfile
    env_file: ./.env
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"

volumes:
  mysql_data:
